### ISSUE TITLE
can't type anything in the address bar

### ISSUE THREAD

**Issue by guaka** [rwweb/webmemex#4]
<img width="480" alt="screen shot 2016-11-07 at 12 29 53" src="https://cloud.githubusercontent.com/assets/54728/20056336/eb1241a8-a4e5-11e6-9350-a87cfb54f68f.png">

**Comment by Treora** [comment]
Should be fixed now, at least for new users. If the problem persists for any existing user, you may have to reload the app a few times, or perhaps empty your storage and restore it afterwards (see #1), in order to get the initially displayed items in the storage.

The problem was that automatically created docs were removed from storage when older application state was loaded from PouchDB, if that loading was not finished in time. Hard-coding their `docId`s should fix this. Some stuff should obviously be structurally changed, but this fix is good enough for the proof of concept.
